realsense2_camera:
  ros__parameters:
    align_depth: true
    enable_color: true
    enable_depth: true
    enable_gyro: false
    enable_accel: false
    unite_imu_method: ""
    depth_module.profile: 640x480x30
    rgb_camera.profile: 640x480x30


